# Generated by Django 4.0.4 on 2022-05-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(max_length=500, upload_to='post-media'),
        ),
    ]
